[package]
name = "restic-dl"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.12.1", default-features = false, features = ["with-axum"] }
askama_axum = "0.4.0"
axum = { version = "0.7.5", features = ["macros"] }
blake3 = "1.5.1"
rustic_backend = { path = "../rustic_core/crates/backend", version = "0.1.1", default-features = false }
rustic_core = { path = "../rustic_core/crates/core", version = "0.2.0" }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
tokio = { version = "1.37.0", features = ["full"] }

[profile.dev.package."*"]
opt-level = 3
