name: Build binary

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
      - "test-release"

jobs:
  build:
    name: Build - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux (x86)
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            name: restic-dl-linux-x86_64.tar.gz

          - os_name: Linux (aarch64)
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            name: restic-dl-linux-aarch64.tar.gz

          - os_name: macOS (aarch64)
            os: macOS-latest
            target: aarch64-apple-darwin
            name: restic-dl-macOS-aarch64.tar.gz

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2

      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.platform.target, 'musl')

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Build assets
        run: npm run prod

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"

      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar czvf ../../../${{ matrix.platform.name }} restic-dl
          cd -
        if: |
          ( startsWith( github.ref, 'refs/tags/v' ) ||
            github.ref == 'refs/tags/test-release' )

      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: restic-dl-${{ matrix.platform.os_name }}
          path: "restic-dl-*"
        if: github.ref == 'refs/tags/test-release'

      # - name: Publish GitHub release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     draft: true
      #     files: "restic-dl-*"
      #     body_path: Changes.md
      #   if: matrix.toolchain == 'stable' && startsWith( github.ref, 'refs/tags/v' )
